<?php

namespace AppBundle\Repository;

/**
 * ProdutosTesteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutosTesteRepository extends \Doctrine\ORM\EntityRepository
{
}
